### ISSUE TITLE
PID is the same for every windows

### ISSUE THREAD

**Issue by andronat** [sjitech/mac_list_windows_pids#1]
Thanks a lot for writing this tool. Is really nice!

I have 1 problem though, when I use it to find which window of Safari takes all of my CPU, the script prints the same PID for every window. Like this:

```
   2093 12383 {335,237,416,432      }   [Safari]
   2093  8497 {-213,873,202,20      }   [Safari]
   2093  6687 {615,271,416,432      }   [Safari]
   2093  5141 {425,56,590,129       }   [Safari]
   2093  4291 {0,0,16,408           }   [Safari]
   2093  4290 {165,55,376,502       }   [Safari]
   2093  4280 {0,0,16,364           }   [Safari]
   2093  4095 {103,111,416,432      }   [Safari]
   2093  4077 {380,242,416,432      }   [Safari]
   2093  3303 {180,55,346,460       }   [Safari]
   2093  3277 {240,319,416,432      }   [Safari]
   2093  3274 {3,873,585,20         }   [Safari]
   2093  3273 {425,56,590,129       }   [Safari]
```

But from the Activity Monitor I can see that each window has a different PID. The problem is that I can not match this list with Activity Monitor and thus I can not find which window is causing the problem :/

**Comment by jjqq2013** [comment]
Thanks for your report. 
It does have the problem. 
Unfortunately i have no way to resolve this, it seems be a bug of Quartz API.

**Comment by jjqq2013** [comment]
You can use "lsappinfo" command, it shows correct pid for safari, but not good for title.
