### ISSUE TITLE
ImportError: No module named Quartz

### ISSUE THREAD

**Issue by sompylasar** [sjitech/mac_list_windows_pids#2]
```
Traceback (most recent call last):
  File "lswin.py", line 3, in <module>
    import Quartz
ImportError: No module named Quartz
```

Please expand the README with how to install that on a clean machine.

**Comment by sompylasar** [comment]
What's missing is: `pip install pyobjc-framework-Quartz`

https://github.com/SavinaRoja/PyUserInput/issues/13#issuecomment-104205226

**Comment by jjqq2013** [comment]
thank you! I will add it to document.

**Comment by sompylasar** [comment]
Fixed via https://github.com/sjitech/mac_list_windows_pids/commit/6c65bcd0ab8ad64d28143d3af682bb958fb5f109
