### ISSUE TITLE
Hey, thanks!

### ISSUE THREAD

**Issue by tleeuwenburg** [sjitech/mac_list_windows_pids#3]
No issue! Just used your code to track down a weird modal dialog box I couldn't close directly. Awesome!

**Comment by jjqq2013** [comment]
Nice! Thank you for your feedback.

**Comment by cameo69** [comment]
Hi, could you give me any hint why I am getting this error?
  File "lswin.py", line 12
    print 'PID'.rjust(7) + ' ' + 'WinID'.rjust(5) + '  ' + 'x,y,w,h'.ljust(21) + ' ' + '\t[Title] SubTitle'
              ^
SyntaxError: invalid syntax
