### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cameo69** [sjitech/mac_list_windows_pids#4]
Hi, could you give me any hint why I am getting this error?

File "lswin.py", line 12
print 'PID'.rjust(7) + ' ' + 'WinID'.rjust(5) + ' ' + 'x,y,w,h'.ljust(21) + ' ' + '\t[Title] SubTitle'
^
SyntaxError: invalid syntax

Running this with python v3.7.4 from brew on Mac Catalina.

**Comment by jjqq2013** [comment]
sorry, the script seems does not work on python 3+, 
it should be `print('PID'.rjust(7) + ' ' + 'WinID'.rjust(5) + '  ' + 'x,y,w,h'.ljust(21) + ' ' + '\t[Title] SubTitle')`

**Comment by cameo69** [comment]
Ah, tnx, ran it with python 2 and it works.
